# Generated by Django 5.2 on 2025-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='titleImage',
            field=models.ImageField(default='coming.jpg', upload_to='project_images/'),
        ),
    ]
