# Generated by Django 5.2 on 2025-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='HydePark', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='engineers',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='project',
            name='equipments',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='project',
            name='execution_period',
            field=models.CharField(default='Giza', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.CharField(default='Lorem ipsum', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Giza', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.IntegerField(default=10),
        ),
    ]
