# Generated by Django 5.2 on 2025-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_client_project_engineers_project_equipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='million',
            field=models.IntegerField(default=2),
        ),
    ]
